spring:
  application:
    name: eureka-server

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#    #    注册开关
#    registerWithEureka: false
#    #    检索服务
#    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0